name: Check Buildability

on:
  push:

env:
  W_AUTH_DATABASE_URL: ${{ secrets.W_AUTH_DATABASE_URL }}
  ATSUOCODER_DATABASE_URL: ${{ secrets.ATSUOCODER_DATABASE_URL }}
  LOGIN_URL: ${{ secrets.LOGIN_URL }}
  SIGNUP_URL: ${{ secrets.SIGNUP_URL }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@atsuo-tech"

      - run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run clean
      - run: npm run build

  bump-version:
    if: ${{ github.ref == 'refs/heads/canary' }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@atsuo-tech"

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump npm version
        run: |
          npm version prerelease --preid canary
          git push origin HEAD:canary --follow-tags

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: $(git describe --tags --abbrev=0)
          release_name: Canary Release $(git describe --tags --abbrev=0)
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
