name: npm version on merge
permissions:
  contents: write
  packages: write

on:
  workflow_run:
    workflows: ["Check Buildability"]
    types:
      - completed

jobs:
  bump-version:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/canary' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@atsuo-tech"
      - run: npm ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump npm version
        run: |
          npm version patch --preid=canary
          git push origin HEAD:canary
